version: '3.8'

services:

  artemis:
    container_name: artemis
    image: quay.io/artemiscloud/activemq-artemis-broker:artemis.2.32.0
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      AMQ_USER: artemis
      AMQ_PASSWORD: artemis

  kafka:
    container_name: kafka
    image: apache/kafka:3.7.0
    ports:
      - 9092:9092

  greenmail:
    container_name: greenmail
    image: greenmail/standalone:2.0.0
    ports:
      - "3025:3025"
      - "3110:3110"
      - "3143:3143"
      - "3465:3465"
      - "3993:3993"
      - "3995:3995"
      - "9980:8080"